export type Country = {
	iso: string;   // ISO-2 country code (for flag SVG filename)
	code: string;  // Calling code
	label: string; // Country name
};

export const COUNTRIES: Country[] = [
	{ iso: 'af', code: '+93', label: 'Afghanistan' },
	{ iso: 'al', code: '+355', label: 'Albania' },
	{ iso: 'dz', code: '+213', label: 'Algeria' },
	{ iso: 'ad', code: '+376', label: 'Andorra' },
	{ iso: 'ao', code: '+244', label: 'Angola' },
	{ iso: 'ag', code: '+1-268', label: 'Antigua and Barbuda' },
	{ iso: 'ar', code: '+54', label: 'Argentina' },
	{ iso: 'am', code: '+374', label: 'Armenia' },
	{ iso: 'au', code: '+61', label: 'Australia' },
	{ iso: 'at', code: '+43', label: 'Austria' },
	{ iso: 'az', code: '+994', label: 'Azerbaijan' },

	{ iso: 'bs', code: '+1-242', label: 'Bahamas' },
	{ iso: 'bh', code: '+973', label: 'Bahrain' },
	{ iso: 'bd', code: '+880', label: 'Bangladesh' },
	{ iso: 'bb', code: '+1-246', label: 'Barbados' },
	{ iso: 'by', code: '+375', label: 'Belarus' },
	{ iso: 'be', code: '+32', label: 'Belgium' },
	{ iso: 'bz', code: '+501', label: 'Belize' },
	{ iso: 'bj', code: '+229', label: 'Benin' },
	{ iso: 'bt', code: '+975', label: 'Bhutan' },
	{ iso: 'bo', code: '+591', label: 'Bolivia' },
	{ iso: 'ba', code: '+387', label: 'Bosnia and Herzegovina' },
	{ iso: 'bw', code: '+267', label: 'Botswana' },
	{ iso: 'br', code: '+55', label: 'Brazil' },
	{ iso: 'bn', code: '+673', label: 'Brunei' },
	{ iso: 'bg', code: '+359', label: 'Bulgaria' },
	{ iso: 'bf', code: '+226', label: 'Burkina Faso' },
	{ iso: 'bi', code: '+257', label: 'Burundi' },

	{ iso: 'kh', code: '+855', label: 'Cambodia' },
	{ iso: 'cm', code: '+237', label: 'Cameroon' },
	{ iso: 'ca', code: '+1', label: 'Canada' },
	{ iso: 'cv', code: '+238', label: 'Cape Verde' },
	{ iso: 'cf', code: '+236', label: 'Central African Republic' },
	{ iso: 'td', code: '+235', label: 'Chad' },
	{ iso: 'cl', code: '+56', label: 'Chile' },
	{ iso: 'cn', code: '+86', label: 'China' },
	{ iso: 'co', code: '+57', label: 'Colombia' },
	{ iso: 'km', code: '+269', label: 'Comoros' },
	{ iso: 'cg', code: '+242', label: 'Congo' },
	{ iso: 'cr', code: '+506', label: 'Costa Rica' },
	{ iso: 'hr', code: '+385', label: 'Croatia' },
	{ iso: 'cu', code: '+53', label: 'Cuba' },
	{ iso: 'cy', code: '+357', label: 'Cyprus' },
	{ iso: 'cz', code: '+420', label: 'Czech Republic' },

	{ iso: 'dk', code: '+45', label: 'Denmark' },
	{ iso: 'dj', code: '+253', label: 'Djibouti' },
	{ iso: 'dm', code: '+1-767', label: 'Dominica' },
	{ iso: 'do', code: '+1-809', label: 'Dominican Republic' },

	{ iso: 'ec', code: '+593', label: 'Ecuador' },
	{ iso: 'eg', code: '+20', label: 'Egypt' },
	{ iso: 'sv', code: '+503', label: 'El Salvador' },
	{ iso: 'gq', code: '+240', label: 'Equatorial Guinea' },
	{ iso: 'er', code: '+291', label: 'Eritrea' },
	{ iso: 'ee', code: '+372', label: 'Estonia' },
	{ iso: 'et', code: '+251', label: 'Ethiopia' },

	{ iso: 'fi', code: '+358', label: 'Finland' },
	{ iso: 'fr', code: '+33', label: 'France' },

	{ iso: 'ge', code: '+995', label: 'Georgia' },
	{ iso: 'de', code: '+49', label: 'Germany' },
	{ iso: 'gh', code: '+233', label: 'Ghana' },
	{ iso: 'gr', code: '+30', label: 'Greece' },
	{ iso: 'gd', code: '+1-473', label: 'Grenada' },
	{ iso: 'gt', code: '+502', label: 'Guatemala' },
	{ iso: 'gn', code: '+224', label: 'Guinea' },
	{ iso: 'gw', code: '+245', label: 'Guinea-Bissau' },
	{ iso: 'gy', code: '+592', label: 'Guyana' },

	{ iso: 'ht', code: '+509', label: 'Haiti' },
	{ iso: 'hn', code: '+504', label: 'Honduras' },
	{ iso: 'hu', code: '+36', label: 'Hungary' },

	{ iso: 'is', code: '+354', label: 'Iceland' },
	{ iso: 'in', code: '+91', label: 'India' },
	{ iso: 'id', code: '+62', label: 'Indonesia' },
	{ iso: 'ir', code: '+98', label: 'Iran' },
	{ iso: 'iq', code: '+964', label: 'Iraq' },
	{ iso: 'ie', code: '+353', label: 'Ireland' },
	{ iso: 'il', code: '+972', label: 'Israel' },
	{ iso: 'it', code: '+39', label: 'Italy' },

	{ iso: 'jp', code: '+81', label: 'Japan' },
	{ iso: 'jo', code: '+962', label: 'Jordan' },

	{ iso: 'kz', code: '+7', label: 'Kazakhstan' },
	{ iso: 'ke', code: '+254', label: 'Kenya' },
	{ iso: 'kw', code: '+965', label: 'Kuwait' },

	{ iso: 'lv', code: '+371', label: 'Latvia' },
	{ iso: 'lb', code: '+961', label: 'Lebanon' },
	{ iso: 'lr', code: '+231', label: 'Liberia' },
	{ iso: 'ly', code: '+218', label: 'Libya' },
	{ iso: 'li', code: '+423', label: 'Liechtenstein' },
	{ iso: 'lt', code: '+370', label: 'Lithuania' },
	{ iso: 'lu', code: '+352', label: 'Luxembourg' },

	{ iso: 'my', code: '+60', label: 'Malaysia' },
	{ iso: 'mv', code: '+960', label: 'Maldives' },
	{ iso: 'mx', code: '+52', label: 'Mexico' },
	{ iso: 'mc', code: '+377', label: 'Monaco' },
	{ iso: 'mn', code: '+976', label: 'Mongolia' },
	{ iso: 'ma', code: '+212', label: 'Morocco' },

	{ iso: 'np', code: '+977', label: 'Nepal' },
	{ iso: 'nl', code: '+31', label: 'Netherlands' },
	{ iso: 'nz', code: '+64', label: 'New Zealand' },
	{ iso: 'ng', code: '+234', label: 'Nigeria' },
	{ iso: 'no', code: '+47', label: 'Norway' },

	{ iso: 'pk', code: '+92', label: 'Pakistan' },
	{ iso: 'ph', code: '+63', label: 'Philippines' },
	{ iso: 'pl', code: '+48', label: 'Poland' },
	{ iso: 'pt', code: '+351', label: 'Portugal' },

	{ iso: 'qa', code: '+974', label: 'Qatar' },

	{ iso: 'ro', code: '+40', label: 'Romania' },
	{ iso: 'ru', code: '+7', label: 'Russia' },

	{ iso: 'sa', code: '+966', label: 'Saudi Arabia' },
	{ iso: 'sg', code: '+65', label: 'Singapore' },
	{ iso: 'sk', code: '+421', label: 'Slovakia' },
	{ iso: 'si', code: '+386', label: 'Slovenia' },
	{ iso: 'za', code: '+27', label: 'South Africa' },
	{ iso: 'kr', code: '+82', label: 'South Korea' },
	{ iso: 'es', code: '+34', label: 'Spain' },
	{ iso: 'lk', code: '+94', label: 'Sri Lanka' },
	{ iso: 'se', code: '+46', label: 'Sweden' },
	{ iso: 'ch', code: '+41', label: 'Switzerland' },

	{ iso: 'tw', code: '+886', label: 'Taiwan' },
	{ iso: 'th', code: '+66', label: 'Thailand' },
	{ iso: 'tr', code: '+90', label: 'Turkey' },

	{ iso: 'ug', code: '+256', label: 'Uganda' },
	{ iso: 'ua', code: '+380', label: 'Ukraine' },
	{ iso: 'ae', code: '+971', label: 'United Arab Emirates' },
	{ iso: 'gb', code: '+44', label: 'United Kingdom' },
	{ iso: 'us', code: '+1', label: 'United States' },
	{ iso: 'uy', code: '+598', label: 'Uruguay' },

	{ iso: 'uz', code: '+998', label: 'Uzbekistan' },

	{ iso: 've', code: '+58', label: 'Venezuela' },
	{ iso: 'vn', code: '+84', label: 'Vietnam' },

	{ iso: 'ye', code: '+967', label: 'Yemen' },

	{ iso: 'zm', code: '+260', label: 'Zambia' },
	{ iso: 'zw', code: '+263', label: 'Zimbabwe' },
];
